services:
  - docker

script:
  # Sprawdź, czy obrazy da się zbudować:
  - cd stable/containers && make build
  
  # Sprawdź, czy docker-compose wystartuje
  - cd stable/stack && docker-compose pull
  - cd stable/stack && docker-compose up -d
  - cd stable/stack && docker-compose exec appserver bpp-manage.py createsuperuser --username admin --noinput --email michal.dtz@gmail.com
