version: '2'
services:

  redis:
    image: redis:latest

  db:
    image: mpasternak79/postgres:12
    volumes:
      - psql_db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: bpp

  appserver:
    image: mpasternak79/bpp-appserver:unstable
    env_file: appserver.env
    depends_on:
      - db
    volumes:
      - staticroot:/staticroot

  celery:
    image: mpasternak79/bpp-celery:unstable
    env_file: appserver.env
    depends_on:
      - appserver

  webserver:
    image: mpasternak79/bpp-webserver:latest
    depends_on:
      - appserver
      - celery
    ports:
      - 8080:80
    volumes:
      - staticroot:/var/www/html/staticroot

volumes:
  psql_db:
  staticroot: