FROM circleci/python:3.6-node

RUN sudo apt-get update && sudo apt-get install -y gettext

WORKDIR /home/circleci

RUN git clone https://github.com/iplweb/bpp/

WORKDIR bpp

RUN sudo npm install -g grunt-cli

RUN pipenv install 

RUN pipenv run make assets-production

RUN pipenv run python setup.py bdist_wheel

RUN ln -las dist

#FROM python:3.6
#RUN pip install bpp-iplweb==1.0.26
