FROM circleci/python:3.6-node
RUN sudo apt-get update && sudo apt-get install -y gettext
WORKDIR /home/circleci
RUN git clone https://github.com/iplweb/bpp/
WORKDIR bpp
RUN sudo npm install -g grunt-cli
RUN pipenv install 
RUN yarn install
RUN grunt build
RUN yarn install --prod
RUN pipenv run python src/manage.py collectstatic --noinput -v0 --traceback
RUN pipenv run python src/manage.py compress --force -v0 --traceback
RUN pipenv run python setup.py bdist_wheel

FROM python:3.6
COPY --from=0 /home/circleci/bpp/dist/bpp_iplweb-*-none-any.whl /
RUN pip install /*whl
